name: Docker

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Metadata
      id: metadata
      uses: docker/metadata-action@v4
      with:
        images: |
          lxgaming/nexus3
          ghcr.io/lxgaming/nexus3
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GHCR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Build and Push
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      run: echo "context=https://github.com/sonatype/docker-nexus3.git#${GITHUB_REF_NAME#*v}" >> $GITHUB_ENV
    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: ${{ env.context }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        labels: ${{ steps.metadata.outputs.labels }}
        tags: ${{ steps.metadata.outputs.tags }}