name: Docker

on:
  push:
    tags: [ 'v*.*.*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Metadata
      id: metadata
      uses: docker/metadata-action@v5
      with:
        images: |
          lxgaming/nexus3
          ghcr.io/lxgaming/nexus3
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
        flavor: |
          latest=true
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GHCR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Build and Push
      run: echo "context=https://github.com/sonatype/docker-nexus3.git#${GITHUB_REF_NAME#*v}" >> $GITHUB_ENV
    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        context: ${{ env.context }}
        file: ./Dockerfile.java17
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        labels: ${{ steps.metadata.outputs.labels }}
        tags: ${{ steps.metadata.outputs.tags }}
  docker-alpine:
    name: Docker Alpine
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Metadata
      id: metadata
      uses: docker/metadata-action@v5
      with:
        images: |
          lxgaming/nexus3
          ghcr.io/lxgaming/nexus3
        tags: |
          type=raw,value=alpine
          type=semver,pattern={{version}},suffix=-alpine
          type=semver,pattern={{major}}.{{minor}},suffix=-alpine
        flavor: |
          latest=false
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GHCR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Build and Push
      run: echo "context=https://github.com/sonatype/docker-nexus3.git#${GITHUB_REF_NAME#*v}" >> $GITHUB_ENV
    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        context: ${{ env.context }}
        file: ./Dockerfile.alpine.java17
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        labels: ${{ steps.metadata.outputs.labels }}
        tags: ${{ steps.metadata.outputs.tags }}